### ISSUE TITLE
[BUG] Margin Tool Displays NaN and 

### ISSUE THREAD

**Issue by Kolomona** [Meigs2/REvernus#14]
**Describe the bug**
When exporting file from Eve Market sometimes the Margin Tool will display NaN and not have numbers about the item.

**To Reproduce**
Open Margin tool and repeatedly click the Export to File button in the Eve Market Window
It seems to happen randomly

**Expected behavior**
Margin Tool should update with correct information

**Screenshots**
https://cdn.kolomona.com/media/images/revernus/NaN-19-10-15.gif

**Desktop (please complete the following information):**
 - OS: [Win10, Win8.1]
 - Browser [NA]
 - Version [NA]

**Additional context**
I believe it's some sort of timing error. If I put the thread to sleep for as little as 5 milliseconds the problem dissapears.
I will create a pull request as soon as I figure out how.
I think it may be due to my slow computers.
I've reproduced on my desktop as well as my laptop.

**Comment by Meigs2** [comment]
I've seen this happen before and odds are its something to do with the FileSystemWatcher being picky about something. It's a fickle beast. As you said, sometimes timing can be an issue. I'll look into it later, but if you've got a solution but don't know how to conteibute/make a pull request do the following:

1. Fork the repo on Github to your account
1. Create a new branch from the develop branch in your fork for the fix
1. Push your changes to your fix branch
1. Create a pull request from your fix branch into my develop branch

Done! Appreciate it :)
