### ISSUE TITLE
[BUG] Margin Tool Auto Copy HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN)

### ISSUE THREAD

**Issue by Kolomona** [Meigs2/REvernus#16]
**Describe the bug**
When exporting file from Eve Market and either "Sell Copy" or "Buy Copy" radio buttons are selected the program throws exception (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))

**To Reproduce**
Debug with VS2019
Open Market Tool
Select either "Sell Copy" or "Buy Copy" option
Export file From Eve Market

**Expected behavior**
Either the buy price or sell price should be copied into the clipboard

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Win10]
 
**Additional context**
It works when using Clipboard.SetDataObject() instead of Clipboard.SetText()
Will issue a PR

I found some info here
https://stackoverflow.com/questions/12769264/openclipboard-failed-when-copy-pasting-data-from-wpf-datagrid

**Comment by Meigs2** [comment]
Fixed in #17
