### ISSUE TITLE
No support in NET 3.0

### ISSUE THREAD

**Issue by Kogasar** [Meigs2/REvernus#34]
Good day.
No support for NET 3.0 in the latest version of Visual Studio 2019

Unsupported
This version of Visual Studio is unable to open the following projects. The project types may not be installed or this version of Visual Studio may not support them. 
For more information on enabling these project types or otherwise migrating your assets, please see the details in the "Migration Report" displayed after clicking OK.
	 - REvernus, ".\REvernus-master\REvernus\REvernus.csproj"
	 - EVEStandard, ".\REvernus-master\EVEStandard\EVEStandard.csproj"

No changes required
These projects can be opened in Visual Studio 2015, Visual Studio 2013, Visual Studio 2012, and Visual Studio 2010 SP1 without changing them.
	 - REvernus, ".\REvernus-master\REvernus.sln"

**Comment by Meigs2** [comment]
The project is for sure compatable with .Net Core 3.1, try changing the project type to that.

The `develop` branch should also already be using .Net Core 3.1, so try using that.
