### ISSUE TITLE
React/Redux version?

### ISSUE THREAD

**Issue by DouglasThom** [Meigs2/REvernus#7]
I imagine you are doing this in C# because that's what you learned as a CS student.

If there is any remote chance you might consider doing this with something like a Node server API behind a React/Redux application then it would open it up to anything with a browser, would make transitioning to mobile very easy, and I could help with the coding! :)

Feel free to just reject this. I just thought it would be better to ask if there was a remote chance rather than not ask and realize later I could have been more help.

Thanks!

**Comment by Meigs2** [comment]
There are (currently) no plans to make any form of REvernus web based at the moment, as it is beyond the intended scope of the project. That being said, in the future we plan to add some some sort of local server that you can host while Evernus is running so you can check your orders, etc without having to actually open the application, or connect from another device, like your phone

If we do consider doing something, we'll re-open this issue! 😄
