### ISSUE TITLE
[BUG] After the server reset, app won't fetch orders anymore

### ISSUE THREAD

**Issue by killerog** [Meigs2/REvernus#8]
**Describe the bug**
After the server gets restarted, the app doesn't seem to respond anymore to inputs (no crashes though).

**To Reproduce**
1. Select a character from the dropdown
2. Fetch data with the button without a label
3. Do stuff on the market
4. Wait for the daily server reset
5. Try to fetch data with the button again.

**Expected behavior**
Data to be fetched, or an error that I need to restart the program

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 7

**Comment by Meigs2** [comment]
I'm closing this issue until I get to investigate further, but rest assured this will be fixed. There's a few issues with character auth refreshing at the moment, so this will be addressed before the planned December public release. I'll re-open the issue when this gets fixed. Sorry for the late response!
