### ISSUE TITLE
[BUG] Margin tool has troubles with similar names of items

### ISSUE THREAD

**Issue by killerog** [Meigs2/REvernus#9]
**Describe the bug**
If you try to get data from items with similar names, the tool sometimes doesn't know what to do anymore and shows incorrect data or NaN.

**To Reproduce**
1. Go to '200mm AutoCannon I'
2. Export market data to file
3. See that data is correctly loaded into margin tool (screenshot 1)
4. Go to '200mm AutoCannon II'
2. Export market data to file
3. See that buy orders aren't loaded and sell orders only partially (screenshot 2 and 3)
1. Go to '200mm AutoCannon I'
2. Export market data to file
3. See that no data is loaded, it just shows NaN (screenshot 1)

**Expected behavior**
Market data is shown every time data is exported

**Screenshots**
https://imgur.com/a/SLIauxs

**Comment by rebelEpik** [comment]
Fixed per PR 13
